export const PRIVATE_FILES = [
  "**/autocomplete/AutocompleteListboxChildren*",
  "**/autocomplete/utils*",
  "**/error-boundary/context*",
  "**/files/createAcceptFromExtensions*",
  "**/form/InputToggleIcon*",
  "**/form/ResizingTextAreaWrapper*",
  "**/form/SliderTrack*",
  "**/form/selectUtils*",
  "**/form/sliderUtils*",
  "**/form/useResizingTextArea*",
  "**/form/useSliderDraggable*",
  "**/icon/configureMaterialSymbols*",
  "**/icon/getMaterialSymbolOption*",
  "**/interaction/utils*",
  "**/menu/MenuWidgetKeyboardProvider*",
  "**/menu/utils*",
  "**/positioning/createHorizontalPosition*",
  "**/positioning/createVerticalPosition*",
  "**/storage/internalUtils*",
  "**/tabs/useTabList*",
  "**/tabs/utils*",
  "**/tooltip/useTooltipPosition*",
  "**/tooltip/utils*",
  "**/transition/utils*",
  "**/tree/useTreeMovement*",
];

export const GENERATED_FILE_BANNER =
  "// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY";

export const SYNCED_EXPORTS = [
  "test-utils",
  "test-utils/data-testid",
  "test-utils/jest-globals",
  "test-utils/jest-globals/setup",
  "test-utils/vitest",
  "test-utils/vitest/setup",
  "test-utils/polyfills",
];
